import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Zap,
  Shield,
  Search,
  Accessibility,
  Gauge,
  FileText,
  ArrowRight,
  Globe,
  Lock,
  Image,
  Link2,
  Smartphone,
  CheckCircle2,
  BarChart3,
  Clock,
  Code2,
} from "lucide-react";

const coreFeatures = [
  {
    icon: Gauge,
    title: "Core Web Vitals",
    description:
      "Real performance metrics from Google Chrome's CrUX data. Measure LCP, INP, CLS, and get full Lighthouse performance scores.",
    details: [
      "Largest Contentful Paint (LCP)",
      "Interaction to Next Paint (INP)",
      "Cumulative Layout Shift (CLS)",
      "Full Lighthouse score breakdown",
    ],
  },
  {
    icon: Search,
    title: "SEO Analysis",
    description:
      "Comprehensive on-page SEO audit covering title tags, meta descriptions, headings, canonical URLs, and Open Graph markup.",
    details: [
      "Title tag & meta description",
      "H1-H6 heading hierarchy",
      "Canonical URL validation",
      "Open Graph & robots directives",
    ],
  },
  {
    icon: Accessibility,
    title: "Accessibility Audit",
    description:
      "WCAG-aligned checks for alt text coverage, ARIA labels, form labels, heading order, and keyboard navigation issues.",
    details: [
      "Alt text on all images",
      "ARIA label coverage",
      "Form label associations",
      "Empty link & button detection",
    ],
  },
  {
    icon: Shield,
    title: "Security Headers",
    description:
      "Check 9 critical HTTP security headers including HSTS, CSP, X-Frame-Options, and Referrer-Policy with scoring.",
    details: [
      "HSTS & Content-Security-Policy",
      "X-Frame-Options & X-Content-Type-Options",
      "Referrer-Policy & Permissions-Policy",
      "Server header exposure check",
    ],
  },
  {
    icon: Zap,
    title: "Performance Audit",
    description:
      "Deep performance analysis covering page size, compression, caching, render-blocking resources, and image optimization.",
    details: [
      "Total page size & request count",
      "Gzip/Brotli compression",
      "Cache-Control header analysis",
      "Render-blocking resource detection",
    ],
  },
  {
    icon: Lock,
    title: "SSL/TLS Certificate",
    description:
      "Validate SSL certificates, check expiration dates, verify certificate chains, and ensure proper HTTPS configuration.",
    details: [
      "Certificate expiration check",
      "Chain of trust validation",
      "HTTPS redirect verification",
      "Mixed content detection",
    ],
  },
  {
    icon: Smartphone,
    title: "Mobile Friendliness",
    description:
      "Verify viewport meta tags, responsive design signals, and mobile-specific best practices.",
    details: [
      "Viewport meta tag presence",
      "Responsive layout detection",
      "Touch target sizing",
      "Mobile rendering checks",
    ],
  },
  {
    icon: Link2,
    title: "Broken Link Detection",
    description:
      "Crawl internal and external links concurrently to find broken links, redirects, and accessibility issues.",
    details: [
      "Concurrent link crawling",
      "Internal & external link check",
      "Redirect chain detection",
      "404 & 5xx error reporting",
    ],
  },
  {
    icon: FileText,
    title: "AI-Generated Reports",
    description:
      "Get a client-ready markdown report with prioritized, specific fixes generated by AI — not generic advice.",
    details: [
      "Prioritized actionable fixes",
      "Developer-ready instructions",
      "Markdown export format",
      "Score breakdown by category",
    ],
  },
];

const checks = [
  {
    icon: Globe,
    name: "Page Fetch",
    time: "~150ms",
    description: "Fetches the page and parses HTML content.",
  },
  {
    icon: Lock,
    name: "SSL Check",
    time: "~200ms",
    description: "Validates SSL certificate and HTTPS configuration.",
  },
  {
    icon: Shield,
    name: "Security Headers",
    time: "~100ms",
    description: "Checks 9 critical HTTP security headers.",
  },
  {
    icon: Search,
    name: "SEO Analysis",
    time: "~80ms",
    description: "Analyzes meta tags, headings, and structured data.",
  },
  {
    icon: Accessibility,
    name: "Accessibility",
    time: "~120ms",
    description: "Audits WCAG compliance and accessibility issues.",
  },
  {
    icon: Zap,
    name: "Performance",
    time: "~200ms",
    description: "Measures page size, compression, and caching.",
  },
  {
    icon: Smartphone,
    name: "Mobile Check",
    time: "~80ms",
    description: "Verifies mobile-friendliness and responsive design.",
  },
  {
    icon: Link2,
    name: "Link Check",
    time: "~300ms",
    description: "Crawls and validates all internal and external links.",
  },
  {
    icon: Gauge,
    name: "PageSpeed",
    time: "~2s",
    description: "Fetches Core Web Vitals from Google PageSpeed Insights.",
  },
  {
    icon: FileText,
    name: "AI Report",
    time: "~3s",
    description: "Generates a prioritized, actionable report.",
  },
];

const differentiators = [
  {
    icon: Clock,
    title: "Results in seconds",
    description:
      "Get a full audit report in under 30 seconds. No waiting for batch processing or scheduled crawls.",
  },
  {
    icon: Code2,
    title: "Developer-first output",
    description:
      "Reports are written for developers. Specific file paths, header values, and line references — not vague recommendations.",
  },
  {
    icon: BarChart3,
    title: "Scored and prioritized",
    description:
      "Every check is scored 0-100. Issues are ranked by severity so you know exactly what to fix first.",
  },
  {
    icon: CheckCircle2,
    title: "9 checks, one report",
    description:
      "All checks run in parallel and results are combined into a single, coherent AI-generated report.",
  },
];

export function FeaturesPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden py-24 sm:py-32">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-transparent" />
        <div className="relative mx-auto container px-6 text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border bg-muted/50 px-4 py-1.5 text-sm text-muted-foreground">
            <span className="size-1.5 animate-pulse rounded-full bg-success" />
            9 automated checks
          </div>
          <h1 className="text-4xl font-semibold tracking-tight sm:text-6xl">
            Every check, one
            <br />
            <span className="text-primary">comprehensive report</span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">
            Probe runs nine automated checks against your website and generates
            an AI-powered report with prioritized, specific fixes you can hand
            directly to a developer.
          </p>
          <div className="mt-10 flex items-center justify-center gap-4">
            <Link href="/register">
              <Button size="lg" className="gap-2">
                Start for free
                <ArrowRight className="size-4" />
              </Button>
            </Link>
            <Link href="/#pricing">
              <Button variant="outline" size="lg">
                View pricing
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Core Features */}
      <section className="border-t py-24 sm:py-32">
        <div className="mx-auto container px-6">
          <div className="text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full border bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
              Comprehensive Audits
            </div>
            <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
              Everything you need to audit a website
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
              Nine automated checks covering performance, SEO, accessibility,
              security, and more — plus an AI-generated report.
            </p>
          </div>
          <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {coreFeatures.map((feature) => (
              <div
                key={feature.title}
                className="group rounded-xl border bg-card p-6 transition-all hover:border-primary/20 hover:bg-primary/5 hover:shadow-lg hover:shadow-primary/5"
              >
                <div className="mb-4 flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground">
                  <feature.icon className="size-5" />
                </div>
                <h3 className="font-semibold">{feature.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {feature.description}
                </p>
                <ul className="mt-4 space-y-1.5">
                  {feature.details.map((detail) => (
                    <li
                      key={detail}
                      className="flex items-center gap-2 text-sm text-muted-foreground"
                    >
                      <CheckCircle2 className="size-3.5 shrink-0 text-success" />
                      {detail}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How the scan works */}
      <section className="border-t bg-muted/30 py-24 sm:py-32">
        <div className="mx-auto container px-6">
          <div className="text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full border bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
              Under the Hood
            </div>
            <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
              How the scan works
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
              Nine checks run in parallel, then AI synthesizes everything into a
              single report. The whole process takes under 30 seconds.
            </p>
          </div>
          <div className="mx-auto mt-16 max-w-3xl">
            <div className="space-y-4">
              {checks.map((check, index) => (
                <div
                  key={check.name}
                  className="flex items-center gap-4 rounded-xl border bg-card p-4 transition-all hover:border-primary/20 hover:bg-primary/5"
                >
                  <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <check.icon className="size-5" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3">
                      <h3 className="font-semibold">{check.name}</h3>
                      <span className="font-mono text-xs text-muted-foreground">
                        {check.time}
                      </span>
                    </div>
                    <p className="text-sm text-muted-foreground">
                      {check.description}
                    </p>
                  </div>
                  <div className="hidden font-mono text-xs text-muted-foreground sm:block">
                    Step {index + 1}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Why Probe */}
      <section className="border-t py-24 sm:py-32">
        <div className="mx-auto container px-6">
          <div className="text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full border bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
              Why Probe
            </div>
            <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
              Built for developers, not marketers
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
              Generic SEO tools give you vague tips. Probe gives you specific
              fixes with file paths, header values, and severity scores.
            </p>
          </div>
          <div className="mt-16 grid gap-8 sm:grid-cols-2">
            {differentiators.map((item) => (
              <div
                key={item.title}
                className="rounded-xl border bg-card p-6 transition-all hover:border-primary/20 hover:bg-primary/5 hover:shadow-lg hover:shadow-primary/5"
              >
                <div className="mb-4 flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <item.icon className="size-5" />
                </div>
                <h3 className="font-semibold">{item.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {item.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t bg-muted/30 py-24 sm:py-32">
        <div className="mx-auto container px-6 text-center">
          <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
            Ready to audit your website?
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
            Start with 5 free audits per month. No credit card required.
          </p>
          <div className="mt-10 flex items-center justify-center gap-4">
            <Link href="/register">
              <Button size="lg" className="gap-2">
                Get started for free
                <ArrowRight className="size-4" />
              </Button>
            </Link>
            <Link href="/#pricing">
              <Button variant="outline" size="lg">
                Compare plans
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
